# ============================================================
# Session
# ============================================================
session_name: "test_live32"

# ============================================================
# Acquisition MU32
# ============================================================
Fe: 10000

Tw: 0.3       # longueur fenêtre glissante en s
Th: 0.1       # pas de mise à jour en s

# ============================================================
# Fréquence live
# ============================================================
f_start: 2000.0
f_step: 100.0
delta_f: 20.0

f_min: 100.0
f_max_factor: 0.45

# ============================================================
# Beamforming
# ============================================================
diag_remove : False

# ============================================================
# Fichiers
# ============================================================
geo_name: "32mu.csv"
calib_name: "calib_camera.npz"

# ============================================================
# Grille beamforming angulaire
# ============================================================
Ltheta: 120
Lphi: 240

phi_min: 0.0
phi_max: 360.0

theta_margin_deg: 2.0
theta_max_limit_deg: 89.0

# ============================================================
# Caméra
# ============================================================
cam_index: 1
cam_w: 640
cam_h: 480

cam_offset: [0.02, 0.02, 0.00]
proj_distance_m: 1.0

flip_x: false
mirror_display: false

# ============================================================
# Rendu
# ============================================================
dyn_dB: 3.0
alpha_scale: 0.85
alpha_gamma: 0.85

show_hud: true
show_footer: true
use_trackbar: false

# ============================================================
# Trigger niveau global
# ============================================================
enable_level_trigger: true
level_threshold_dB: 55.0
trig_max_dB: 120.0
trig_scale: 10

