const $=id=>document.getElementById(id);
const v=$("video"),c=$("image"),x=c.getContext("2d",{willReadFrequently:true}),t=$("three"),g=t.getContext("2d");
const work=document.createElement("canvas"),wx=work.getContext("2d",{willReadFrequently:true});
let stream=null,base=null,corners=[],cand=[],pick=false,yaw=-.6,pitch=.4,drag=null;
let live=false,scanning=false,lastProc=0,markers=[],tracks=[],frameNo=0,view0=null,viewDiversity=0;
const F={rear:[],front:[],left:[],right:[],top:[]};
const msg=s=>$("status").textContent=s;
function arucoLine(){const stable=tracks.filter(q=>q.stable).length,tent=tracks.length-stable;const mv=viewDiversity>0.015?"mouvement OK":"bouge latéralement";$("arucoStatus").textContent="ArUco : "+markers.length+"/4 · stables : "+stable+" · provisoires : "+tent+" · "+mv;}
async function startCam(){try{if(stream)stream.getTracks().forEach(a=>a.stop());stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1920},height:{ideal:1080}},audio:false});v.srcObject=stream;await v.play();const s=Math.min(720/v.videoWidth,900/v.videoHeight,1);c.width=Math.max(1,Math.round(v.videoWidth*s));c.height=Math.max(1,Math.round(v.videoHeight*s));work.width=c.width;work.height=c.height;v.hidden=true;c.hidden=false;live=true;base=null;corners=[];cand=[];markers=[];$("shotBtn").disabled=false;$("scanBtn").disabled=false;msg("Caméra active. Cadre les 4 ArUco puis lance Scan auto ArUco.");requestAnimationFrame(liveLoop);}catch(e){msg("Caméra refusée : "+e.message)}}
$("camBtn").onclick=startCam;
$("scanBtn").onclick=()=>{if(!live)return;scanning=!scanning;$("scanBtn").textContent=scanning?"Arrêter scan":"Scan auto ArUco";if(scanning){tracks=[];frameNo=0;view0=null;viewDiversity=0;lastProc=0;msg("Scan actif : garde les 4 ArUco visibles et déplace-toi latéralement de 30 à 60 cm.");}else msg("Scan arrêté.");};
function liveLoop(ts){if(!live)return;if(v.readyState>=2){x.drawImage(v,0,0,c.width,c.height);if(scanning&&ts-lastProc>450){lastProc=ts;processLive();}drawOverlay(false);}requestAnimationFrame(liveLoop);}
function processLive(){wx.drawImage(v,0,0,work.width,work.height);const img=wx.getImageData(0,0,work.width,work.height);markers=window.detectFourMarkers?window.detectFourMarkers(img):[];const by={};markers.forEach(m=>by[m.id]=m);if(by[0]&&by[1]&&by[2]&&by[3]){corners=[by[0].center,by[1].center,by[2].center,by[3].center];cand=detectWhite(img,corners).filter(p=>!nearMarker(p));const H=hom(corners);if(H){const obs=cand.map(p=>{const q=map(H,p);return{u:q.u,v:q.v,x:p.x,y:p.y}}).filter(q=>q.u>=-.08&&q.u<=1.08&&q.v>=-.08&&q.v<=1.08);updateTracks(obs,corners);syncAutoFace();render3();table();}}else{cand=[];}arucoLine();}
function nearMarker(p){for(const m of markers){let r=0;m.corners.forEach(q=>r=Math.max(r,Math.hypot(q.x-m.center.x,q.y-m.center.y)));if(Math.hypot(p.x-m.center.x,p.y-m.center.y)<r*1.3)return true}return false}
function quadSig(q){const d=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),top=d(q[0],q[1]),right=d(q[1],q[2]),bot=d(q[2],q[3]),left=d(q[3],q[0]),d1=d(q[0],q[2]),d2=d(q[1],q[3]);return[Math.log((top+1)/(bot+1)),Math.log((left+1)/(right+1)),Math.log((d1+1)/(d2+1)),Math.log((top+bot+1)/(left+right+1))]}
function updateTracks(obs,q){frameNo++;const sig=quadSig(q);if(!view0)view0=sig.slice();const vd=Math.sqrt(sig.reduce((z,a,i)=>z+(a-view0[i])*(a-view0[i]),0));viewDiversity=Math.max(viewDiversity,vd);tracks.forEach(tr=>tr.hit=false);for(const o of obs){let k=-1,d=1e9;tracks.forEach((tr,i)=>{if(tr.hit||frameNo-tr.last>5)return;const z=Math.hypot(tr.u-o.u,tr.v-o.v);if(z<d){d=z;k=i}});if(k>=0&&d<.05){const tr=tracks[k];tr.s.push([o.u,o.v]);if(tr.s.length>20)tr.s.shift();tr.last=frameNo;tr.hit=true;tr.x=o.x;tr.y=o.y;recalcTrack(tr);}else tracks.push({u:o.u,v:o.v,s:[[o.u,o.v]],last:frameNo,hit:true,sig:.05,stable:false,x:o.x,y:o.y});}tracks=tracks.filter(tr=>frameNo-tr.last<=8);tracks.forEach(recalcTrack);}
function recalcTrack(tr){tr.u=tr.s.reduce((z,a)=>z+a[0],0)/tr.s.length;tr.v=tr.s.reduce((z,a)=>z+a[1],0)/tr.s.length;tr.sig=tr.s.length>1?Math.sqrt(tr.s.reduce((z,a)=>z+(a[0]-tr.u)*(a[0]-tr.u)+(a[1]-tr.v)*(a[1]-tr.v),0)/(tr.s.length-1)):.05;tr.stable=tr.s.length>=4&&tr.sig<.014&&viewDiversity>0.015;}
function syncAutoFace(){const f=$("face").value,m=Math.max(0,Math.min(.30,+$("margin").value/100));F[f]=tracks.filter(tr=>tr.stable).map(tr=>({u:m/2+tr.u*(1-m),v:m/2+tr.v*(1-m),s:tr.s.slice(),sig:tr.sig,auto:true}));}
$("fileBtn").onclick=()=>$("file").click();
$("file").onchange=e=>{const f=e.target.files[0];if(!f)return;const im=new Image();im.onload=()=>setImage(im);im.src=URL.createObjectURL(f)};
function setImage(im){live=false;scanning=false;$("scanBtn").textContent="Scan auto ArUco";const s=Math.min(720/im.width,900/im.height,1);c.width=Math.max(1,Math.round(im.width*s));c.height=Math.max(1,Math.round(im.height*s));x.drawImage(im,0,0,c.width,c.height);base=x.getImageData(0,0,c.width,c.height);corners=[];cand=[];markers=[];c.hidden=false;v.hidden=true;drawPhoto();msg("Image chargée. Utilise 4 coins manuels puis Détecter blanc.");}
$("shotBtn").onclick=()=>{if(!v.videoWidth)return;const q=document.createElement("canvas");q.width=v.videoWidth;q.height=v.videoHeight;q.getContext("2d").drawImage(v,0,0);const im=new Image();im.onload=()=>setImage(im);im.src=q.toDataURL("image/jpeg",.92)};
$("cornersBtn").onclick=()=>{if(!base){msg("Capture ou charge une image d’abord.");return}corners=[];cand=[];pick=true;drawPhoto();msg("Tape haut-gauche → haut-droite → bas-droite → bas-gauche.");};
function cp(e){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}
function pip(p,a){let z=false;for(let i=0,j=a.length-1;i<a.length;j=i++){if(((a[i].y>p.y)!=(a[j].y>p.y))&&(p.x<(a[j].x-a[i].x)*(p.y-a[i].y)/(a[j].y-a[i].y)+a[i].x))z=!z}return z}
c.onpointerdown=e=>{if(live)return;const p=cp(e);if(pick){corners.push(p);if(corners.length===4){pick=false;msg("Face définie. Lance Détecter blanc.")}drawPhoto();return}let k=-1,d=1e9;cand.forEach((q,i)=>{const a=Math.hypot(q.x-p.x,q.y-p.y);if(a<d){d=a;k=i}});if(k>=0&&d<24)cand[k].keep=!cand[k].keep;else if(corners.length===4&&pip(p,corners))cand.push({x:p.x,y:p.y,r:7,keep:true});drawPhoto()};
function drawPhoto(){if(base)x.putImageData(base,0,0);drawOverlay(true)}
function drawOverlay(photo){if(corners.length){x.strokeStyle="#55d6be";x.fillStyle="#55d6be";x.lineWidth=3;x.beginPath();corners.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));if(corners.length===4)x.closePath();x.stroke();corners.forEach((p,i)=>{x.beginPath();x.arc(p.x,p.y,7,0,7);x.fill();x.fillStyle="#07100e";x.font="bold 11px sans-serif";x.fillText(String(i),p.x-3,p.y+4);x.fillStyle="#55d6be"})}markers.forEach(m=>{x.strokeStyle="#6db6ff";x.lineWidth=3;x.beginPath();m.corners.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.closePath();x.stroke();x.fillStyle="#6db6ff";x.font="bold 14px sans-serif";x.fillText("ID "+m.id,m.center.x+8,m.center.y-8)});cand.forEach(p=>{x.strokeStyle=p.keep===false?"#ff6b6b":"#ffd166";x.lineWidth=2;x.beginPath();x.arc(p.x,p.y,Math.max(5,p.r||6),0,7);x.stroke()});if(live)tracks.forEach(tr=>{if(frameNo-tr.last>1)return;x.strokeStyle=tr.stable?"#62e392":"#ff9f43";x.lineWidth=tr.stable?3:1.5;x.beginPath();x.arc(tr.x,tr.y,tr.stable?9:6,0,7);x.stroke()});}
$("detectBtn").onclick=()=>{if(!base||corners.length!==4){msg("Il faut une image et 4 coins.");return}cand=detectWhite(base,corners);drawPhoto();msg(cand.length+" candidats. Touche pour exclure/ajouter puis Ajouter vue.");};
function detectWhite(img,poly){const D=img.data,W=img.width,H=img.height,thr=+$("thr").value,B=new Uint8Array(W*H),S=new Uint8Array(W*H);let ax=W,ay=H,bx=0,by=0;poly.forEach(p=>{ax=Math.min(ax,p.x);ay=Math.min(ay,p.y);bx=Math.max(bx,p.x);by=Math.max(by,p.y)});ax=Math.max(0,ax|0);ay=Math.max(0,ay|0);bx=Math.min(W-1,Math.ceil(bx));by=Math.min(H-1,Math.ceil(by));for(let yy=ay;yy<=by;yy++)for(let xx=ax;xx<=bx;xx++){if(!pip({x:xx,y:yy},poly))continue;const i=(yy*W+xx)*4,r=D[i],gg=D[i+1],b=D[i+2],mx=Math.max(r,gg,b),mn=Math.min(r,gg,b),L=(r+gg+b)/3;if(L>=thr&&mx-mn<65)B[yy*W+xx]=1}let out=[];for(let yy=ay;yy<=by;yy++)for(let xx=ax;xx<=bx;xx++){let s=yy*W+xx;if(!B[s]||S[s])continue;let st=[s],A=0,sx=0,sy=0,x0=xx,x1=xx,y0=yy,y1=yy;S[s]=1;while(st.length){let q=st.pop(),qy=(q/W)|0,qx=q-qy*W;A++;sx+=qx;sy+=qy;x0=Math.min(x0,qx);x1=Math.max(x1,qx);y0=Math.min(y0,qy);y1=Math.max(y1,qy);for(const z of [q-1,q+1,q-W,q+W])if(z>=0&&z<W*H&&!S[z]&&B[z]){S[z]=1;st.push(z)}}const ww=x1-x0+1,hh=y1-y0+1,ar=ww/hh,fill=A/(ww*hh);if(A>=7&&A<550&&ww>=3&&hh>=3&&ww<60&&hh<60&&ar>.42&&ar<2.35&&fill>.22&&fill<.98)out.push({x:sx/A,y:sy/A,r:Math.max(5,Math.max(ww,hh)/2),keep:true,a:A})}out.sort((a,b)=>b.a-a.a);const clean=[];for(const p of out)if(!clean.some(q=>Math.hypot(q.x-p.x,q.y-p.y)<Math.max(8,.6*(q.r+p.r))))clean.push(p);return clean;}
function solve(A,b){const n=b.length,M=A.map((r,i)=>r.slice().concat([b[i]]));for(let k=0;k<n;k++){let m=k;for(let i=k+1;i<n;i++)if(Math.abs(M[i][k])>Math.abs(M[m][k]))m=i;[M[k],M[m]]=[M[m],M[k]];const p=M[k][k];if(Math.abs(p)<1e-10)return null;for(let j=k;j<=n;j++)M[k][j]/=p;for(let i=0;i<n;i++)if(i!==k){const f=M[i][k];for(let j=k;j<=n;j++)M[i][j]-=f*M[k][j]}}return M.map(r=>r[n])}
function hom(q){const d=[[0,0],[1,0],[1,1],[0,1]],A=[],b=[];for(let i=0;i<4;i++){const X=q[i].x,Y=q[i].y,u=d[i][0],vv=d[i][1];A.push([X,Y,1,0,0,0,-u*X,-u*Y]);b.push(u);A.push([0,0,0,X,Y,1,-vv*X,-vv*Y]);b.push(vv)}const h=solve(A,b);return h&&h.concat([1])}
function map(H,p){const d=H[6]*p.x+H[7]*p.y+1;return{u:(H[0]*p.x+H[1]*p.y+H[2])/d,v:(H[3]*p.x+H[4]*p.y+H[5])/d}}
function rec(p){p.u=p.s.reduce((z,a)=>z+a[0],0)/p.s.length;p.v=p.s.reduce((z,a)=>z+a[1],0)/p.s.length;p.sig=p.s.length>1?Math.sqrt(p.s.reduce((z,a)=>z+(a[0]-p.u)*(a[0]-p.u)+(a[1]-p.v)*(a[1]-p.v),0)/(p.s.length-1)):.04}
function merge(f,u,vv){const ar=F[f];let k=-1,d=1e9;ar.forEach((p,i)=>{const z=Math.hypot(p.u-u,p.v-vv);if(z<d){d=z;k=i}});if(k>=0&&d<.075){ar[k].s.push([u,vv]);rec(ar[k])}else ar.push({u:u,v:vv,s:[[u,vv]],sig:.04});}
$("addBtn").onclick=()=>{if(corners.length!==4){msg("Définis les coins.");return}const H=hom(corners),a=cand.filter(p=>p.keep!==false),f=$("face").value;if(!H||!a.length){msg("Aucun point retenu.");return}a.forEach(p=>{const q=map(H,p);if(q.u>=-.05&&q.u<=1.05&&q.v>=-.05&&q.v<=1.05)merge(f,q.u,q.v)});render3();table();msg(a.length+" observations ajoutées à "+f+".");};
function xyz(f,u,vv){const a=2*u,z=2*(1-vv);if(f==="rear")return[a,2,z];if(f==="front")return[2-a,0,z];if(f==="left")return[0,2-a,z];if(f==="right")return[2,a,z];return[a,2*(1-vv),2]}
function points(){const a=[];Object.entries(F).forEach(([f,ar])=>ar.forEach(p=>a.push({f:f,p:p,X:xyz(f,p.u,p.v)})));return a}
function pr(P){let X=P[0]-1,Y=P[1]-1,Z=P[2]-1,cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),a=cy*X-sy*Y,b=sy*X+cy*Y,c2=Z,b2=cp*b-sp*c2,z2=sp*b+cp*c2,s=t.width*.30/(5.2-b2);return[t.width/2+a*s*3.25,t.height/2-z2*s*3.25,b2]}
function render3(){g.fillStyle="#080a0d";g.fillRect(0,0,t.width,t.height);const V=[[0,0,0],[2,0,0],[2,2,0],[0,2,0],[0,0,2],[2,0,2],[2,2,2],[0,2,2]],E=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]];g.strokeStyle="#66717d";g.lineWidth=2;E.forEach(e=>{const a=pr(V[e[0]]),b=pr(V[e[1]]);g.beginPath();g.moveTo(a[0],a[1]);g.lineTo(b[0],b[1]);g.stroke()});points().forEach(o=>{const q=pr(o.X),rr=Math.min(24,5+(o.p.sig||.02)*150);g.strokeStyle="rgba(109,182,255,.65)";g.beginPath();g.arc(q[0],q[1],rr,0,7);g.stroke();g.fillStyle=o.p.s&&o.p.s.length>1?"#62e392":"#ffd166";g.beginPath();g.arc(q[0],q[1],5,0,7);g.fill()});$("count").textContent=points().length+" micros reconstruits"}
function table(){const p=points();let s="<table><tr><th>ID</th><th>Face</th><th>X</th><th>Y</th><th>Z</th><th>vues</th></tr>";p.slice(0,40).forEach((o,i)=>s+="<tr><td>M"+String(i+1).padStart(3,"0")+"</td><td>"+o.f+"</td><td>"+o.X[0].toFixed(3)+"</td><td>"+o.X[1].toFixed(3)+"</td><td>"+o.X[2].toFixed(3)+"</td><td>"+(o.p.s?o.p.s.length:1)+"</td></tr>");$("table").innerHTML=p.length?s+"</table>":""}
function tp(e){const r=t.getBoundingClientRect();return[e.clientX-r.left,e.clientY-r.top]}
t.onpointerdown=e=>{drag=tp(e);t.setPointerCapture(e.pointerId)};t.onpointermove=e=>{if(!drag)return;const p=tp(e);yaw+=(p[0]-drag[0])*.009;pitch=Math.max(-1.3,Math.min(1.3,pitch+(p[1]-drag[1])*.009));drag=p;render3()};t.onpointerup=()=>drag=null;
$("resetBtn").onclick=()=>{yaw=-.6;pitch=.4;render3()};$("clearBtn").onclick=()=>{Object.keys(F).forEach(k=>F[k]=[]);tracks=[];render3();table();arucoLine()};
$("csvBtn").onclick=()=>{let s="id,face,x_m,y_m,z_m,n_views\n";points().forEach((o,i)=>s+="M"+String(i+1).padStart(3,"0")+","+o.f+","+o.X[0]+","+o.X[1]+","+o.X[2]+","+(o.p.s?o.p.s.length:1)+"\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([s],{type:"text/csv"}));a.download="cube_mems.csv";a.click()};
render3();arucoLine();