const $=id=>document.getElementById(id);
const video=$("video"),canvas=$("image"),ctx=canvas.getContext("2d",{willReadFrequently:true}),three=$("three"),g=three.getContext("2d");
const work=document.createElement("canvas"),wctx=work.getContext("2d",{willReadFrequently:true});
let stream=null,live=false,scanning=false,lastProc=0,markers=[],pose=null,poseSpread=0,tracks=[],frameNo=0,manualBase=null,manualCorners=[],manualCandidates=[],manualPick=false,lastWhites=[],lastCenterDeltaMm=null;
let yaw=-0.65,pitch=0.42,drag=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const norm=a=>Math.hypot(a[0],a[1],a[2]);
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
const sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]];
const add=(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]];
const mul=(a,s)=>[a[0]*s,a[1]*s,a[2]*s];
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const unit=a=>{const n=norm(a)||1;return[a[0]/n,a[1]/n,a[2]/n]};
const msg=s=>$("status").textContent=s;
function settings(){return{marker:+$("markerSize").value/100,S:+$("faceSize").value,d:+$("planeOffset").value/100,delta:+$("planeDelta").value/100,hfov:+$("hfov").value*Math.PI/180,thr:+$("thr").value,assoc:+$("assoc").value/100,baseline:+$("baseline").value/100,centerMode:$("centerMode").value}}
$("thr").oninput=()=>{$("thrOut").textContent=$("thr").value};
$("planeDelta").oninput=()=>{$("deltaMetric").textContent="±"+$("planeDelta").value+" cm"};
function Kpars(W,H){const s=settings(),fx=(W/2)/Math.tan(s.hfov/2);return{fx:fx,fy:fx,cx:W/2,cy:H/2}}
function solve(A,b){const n=b.length,M=A.map((r,i)=>r.slice().concat([b[i]]));for(let k=0;k<n;k++){let m=k;for(let i=k+1;i<n;i++)if(Math.abs(M[i][k])>Math.abs(M[m][k]))m=i;[M[k],M[m]]=[M[m],M[k]];let p=M[k][k];if(Math.abs(p)<1e-10)return null;for(let j=k;j<=n;j++)M[k][j]/=p;for(let i=0;i<n;i++)if(i!==k){let f=M[i][k];for(let j=k;j<=n;j++)M[i][j]-=f*M[k][j]}}return M.map(r=>r[n])}
function homXY(src,dst){const A=[],b=[];for(let i=0;i<4;i++){const X=src[i][0],Y=src[i][1],u=dst[i].x,v=dst[i].y;A.push([X,Y,1,0,0,0,-u*X,-u*Y]);b.push(u);A.push([0,0,0,X,Y,1,-v*X,-v*Y]);b.push(v)}const h=solve(A,b);return h&&h.concat([1])}
function markerGlobalCenter(id){const S=settings().S;if(id===0)return[0,0,0];if(id===1)return[S,0,0];if(id===2)return[S,S,0];return[0,S,0]}
function applyR(p,R){return add(add(mul(R[0],p[0]),mul(R[1],p[1])),mul(R[2],p[2]))}
function poseFromMarker(m,W,H){const s=settings(),q=m.canonicalCorners||m.corners;if(!q||q.length!==4)return null;const a=s.marker/2,src=[[-a,-a],[a,-a],[a,a],[-a,a]],Hh=homXY(src,q);if(!Hh)return null;const K=Kpars(W,H),kin=v=>[(v[0]-K.cx*v[2])/K.fx,(v[1]-K.cy*v[2])/K.fy,v[2]];let b1=kin([Hh[0],Hh[3],Hh[6]]),b2=kin([Hh[1],Hh[4],Hh[7]]),b3=kin([Hh[2],Hh[5],1]);let lam=2/(norm(b1)+norm(b2));let r1=unit(mul(b1,lam)),r2t=mul(b2,lam);let r2=unit(sub(r2t,mul(r1,dot(r2t,r1)))),r3=unit(cross(r1,r2)),tt=mul(b3,lam);if(tt[2]<0){r1=mul(r1,-1);r2=mul(r2,-1);r3=unit(cross(r1,r2));tt=mul(tt,-1)}const R=[r1,r2,r3],G=markerGlobalCenter(m.id),tG=sub(tt,applyR(G,R));const C=[-dot(r1,tG),-dot(r2,tG),-dot(r3,tG)];const area=Math.abs(polyArea(q));return{R:R,t:tG,C:C,marker:m,area:area}}
function polyArea(q){let a=0;for(let i=0,j=q.length-1;i<q.length;j=i++)a+=q[j].x*q[i].y-q[i].x*q[j].y;return a/2}
function fusePoses(ps){if(!ps.length)return null;if(ps.length===1){poseSpread=0;return ps[0]}let best=0,bestSum=1e99;for(let i=0;i<ps.length;i++){let s=0;for(let j=0;j<ps.length;j++)s+=norm(sub(ps[i].C,ps[j].C));if(s<bestSum){bestSum=s;best=i}}const ref=ps[best];const ds=ps.map(p=>norm(sub(p.C,ref.C))).sort((a,b)=>a-b);poseSpread=ds[Math.floor(ds.length/2)]||0;return ref}
function project(P,p,W,H){const K=Kpars(W,H),X=add(applyR(P,p.R),p.t);if(X[2]<=0.02)return null;return{x:K.fx*X[0]/X[2]+K.cx,y:K.fy*X[1]/X[2]+K.cy,z:X[2]}}
function rayFromPixel(u,vv,p,W,H){const K=Kpars(W,H),dc=unit([(u-K.cx)/K.fx,(vv-K.cy)/K.fy,1]),R=p.R,dg=unit([dot(R[0],dc),dot(R[1],dc),dot(R[2],dc)]);return{C:p.C.slice(),d:dg}}
function facePolygon(p,W,H,z){const S=settings().S,pts=[[0,0,z],[S,0,z],[S,S,z],[0,S,z]].map(P=>project(P,p,W,H));return pts.every(Boolean)?pts:null}
function pip(p,a){let z=false;for(let i=0,j=a.length-1;i<a.length;j=i++){if(((a[i].y>p.y)!=(a[j].y>p.y))&&(p.x<(a[j].x-a[i].x)*(p.y-a[i].y)/(a[j].y-a[i].y)+a[i].x))z=!z}return z}
function intersectNominal(ray){const s=settings();if(Math.abs(ray.d[2])<1e-8)return null;const l=(s.d-ray.C[2])/ray.d[2];if(l<=0)return null;const P=add(ray.C,mul(ray.d,l));return(P[0]>=-0.1&&P[0]<=s.S+0.1&&P[1]>=-0.1&&P[1]<=s.S+0.1)?P:null}
async function startCam(){try{if(stream)stream.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1920},height:{ideal:1080}},audio:false});video.srcObject=stream;await video.play();const sc=Math.min(780/video.videoWidth,1100/video.videoHeight,1);canvas.width=Math.max(1,Math.round(video.videoWidth*sc));canvas.height=Math.max(1,Math.round(video.videoHeight*sc));work.width=canvas.width;work.height=canvas.height;video.hidden=true;canvas.hidden=false;live=true;manualBase=null;$("scanBtn").disabled=false;$("shotBtn").disabled=false;msg("Caméra active. Lance Scanner, puis garde au moins un ArUco visible.");requestAnimationFrame(loop)}catch(e){msg("Caméra refusée : "+e.message)}}
$("camBtn").onclick=startCam;
$("scanBtn").onclick=()=>{if(!live)return;scanning=!scanning;$("scanBtn").textContent=scanning?"Arrêter scan":"Scanner";if(scanning){lastProc=0;msg("Scan actif : un seul ArUco suffit. Déplace-toi latéralement de 30 à 60 cm.");}else msg("Scan arrêté. Les micros validés restent dans la vue 3D.")};
function loop(ts){if(!live)return;if(video.readyState>=2){ctx.drawImage(video,0,0,canvas.width,canvas.height);if(scanning&&ts-lastProc>320){lastProc=ts;processFrame()}drawLiveOverlay()}requestAnimationFrame(loop)}
function processFrame(){wctx.drawImage(video,0,0,work.width,work.height);const img=wctx.getImageData(0,0,work.width,work.height);markers=window.detectFourMarkers?window.detectFourMarkers(img):[];const ps=markers.map(m=>poseFromMarker(m,work.width,work.height)).filter(Boolean);pose=fusePoses(ps);frameNo++;if(!pose){lastWhites=[];lastCenterDeltaMm=null;updateMetrics(0,0,0);return}const poly=facePolygon(pose,work.width,work.height,settings().d);if(!poly){lastWhites=[];lastCenterDeltaMm=null;updateMetrics(markers.length,0,0);return}const side=markers.length?Math.sqrt(markers.reduce((ss,m)=>ss+Math.abs(polyArea(m.corners)),0)/markers.length):30;const whites=detectWhite(img,poly,side),oranges=detectOrange(img,poly);lastWhites=whites;const deltas=[];for(const q of whites){const rc=rayFromPixel(q.cx,q.cy,pose,work.width,work.height),re=rayFromPixel(q.ex,q.ey,pose,work.width,work.height),Pc=intersectNominal(rc),Pe=intersectNominal(re);if(Pc&&Pe)deltas.push(Math.hypot(Pc[0]-Pe[0],Pc[1]-Pe[1])*1000)}lastCenterDeltaMm=deltas.length?deltas.reduce((a,b)=>a+b,0)/deltas.length:null;const all=whites.concat(oranges);const obs=[];for(const q of all){if(nearMarker(q))continue;const ray=rayFromPixel(q.x,q.y,pose,work.width,work.height),P0=intersectNominal(ray);if(P0)obs.push({x:q.x,y:q.y,kind:q.kind||"white",C:ray.C,d:ray.d,nom:P0})}updateTracks(obs);render3();renderTable();updateMetrics(markers.length,whites.length,oranges.length)}
function nearMarker(p){for(const m of markers){let r=0;m.corners.forEach(q=>r=Math.max(r,Math.hypot(q.x-m.center.x,q.y-m.center.y)));if(Math.hypot(p.x-m.center.x,p.y-m.center.y)<r*1.25)return true}return false}
function detectWhite(img,poly,markerSide){const D=img.data,W=img.width,H=img.height,thr=settings().thr,B=new Uint8Array(W*H),S=new Uint8Array(W*H);let ax=W,ay=H,bx=0,by=0;poly.forEach(p=>{ax=Math.min(ax,p.x);ay=Math.min(ay,p.y);bx=Math.max(bx,p.x);by=Math.max(by,p.y)});ax=clamp(ax|0,0,W-1);ay=clamp(ay|0,0,H-1);bx=clamp(Math.ceil(bx),0,W-1);by=clamp(Math.ceil(by),0,H-1);for(let y=ay;y<=by;y++)for(let x0=ax;x0<=bx;x0++){if(!pip({x:x0,y:y},poly))continue;const i=(y*W+x0)*4,r=D[i],gg=D[i+1],b=D[i+2],mx=Math.max(r,gg,b),mn=Math.min(r,gg,b),L=(r+gg+b)/3;if(L>=thr&&mx-mn<62)B[y*W+x0]=1}const out=[];const minD=Math.max(3,markerSide*.05),maxD=Math.max(18,markerSide*.75),mode=settings().centerMode;for(let y=ay;y<=by;y++)for(let x0=ax;x0<=bx;x0++){const st0=y*W+x0;if(!B[st0]||S[st0])continue;const st=[st0];S[st0]=1;let A=0,sx=0,sy=0,x1=x0,x2=x0,y1=y,y2=y;const boundary=[];while(st.length){const q=st.pop(),qy=(q/W)|0,qx=q-qy*W;A++;sx+=qx;sy+=qy;x1=Math.min(x1,qx);x2=Math.max(x2,qx);y1=Math.min(y1,qy);y2=Math.max(y2,qy);let edge=false;for(const z of [q-1,q+1,q-W,q+W]){if(z<0||z>=W*H||!B[z])edge=true;else if(!S[z]){S[z]=1;st.push(z)}}if(edge)boundary.push([qx,qy])}const ww=x2-x1+1,hh=y2-y1+1,ar=ww/hh,fill=A/(ww*hh),dd=Math.max(ww,hh);if(dd<minD||dd>maxD||A<7||ar<=.5||ar>=2||fill<=.25||fill>=.98)continue;const cx=sx/A,cy=sy/A;let ex=(x1+x2)/2,ey=(y1+y2)/2;if(boundary.length>=6){let mx=0,my=0;for(const p of boundary){mx+=p[0];my+=p[1]}mx/=boundary.length;my/=boundary.length;let cxx=0,cxy=0,cyy=0;for(const p of boundary){const dx=p[0]-mx,dy=p[1]-my;cxx+=dx*dx;cxy+=dx*dy;cyy+=dy*dy}const th=.5*Math.atan2(2*cxy,cxx-cyy),ux=Math.cos(th),uy=Math.sin(th),vx=-uy,vy=ux;let u0=1e9,u1=-1e9,v0=1e9,v1=-1e9;for(const p of boundary){const dx=p[0]-mx,dy=p[1]-my,pu=dx*ux+dy*uy,pv=dx*vx+dy*vy;u0=Math.min(u0,pu);u1=Math.max(u1,pu);v0=Math.min(v0,pv);v1=Math.max(v1,pv)}const mu=(u0+u1)/2,mv=(v0+v1)/2;ex=mx+mu*ux+mv*vx;ey=my+mu*uy+mv*vy}const useEllipse=mode!=="centroid";out.push({x:useEllipse?ex:cx,y:useEllipse?ey:cy,cx:cx,cy:cy,ex:ex,ey:ey,diffPx:Math.hypot(ex-cx,ey-cy),r:dd/2,a:A,kind:"white"})}out.sort((a,b)=>b.a-a.a);const clean=[];for(const p of out)if(!clean.some(q=>Math.hypot(q.x-p.x,q.y-p.y)<Math.max(7,.55*(q.r+p.r))))clean.push(p);return clean}
function detectOrange(img,poly){const D=img.data,W=img.width,H=img.height,B=new Uint8Array(W*H),S=new Uint8Array(W*H);let ax=W,ay=H,bx=0,by=0;poly.forEach(p=>{ax=Math.min(ax,p.x);ay=Math.min(ay,p.y);bx=Math.max(bx,p.x);by=Math.max(by,p.y)});ax=clamp(ax|0,0,W-1);ay=clamp(ay|0,0,H-1);bx=clamp(Math.ceil(bx),0,W-1);by=clamp(Math.ceil(by),0,H-1);for(let y=ay;y<=by;y++)for(let x0=ax;x0<=bx;x0++){if(!pip({x:x0,y:y},poly))continue;const i=(y*W+x0)*4,r=D[i],gg=D[i+1],b=D[i+2];if(r>150&&gg>45&&gg<190&&b<125&&r>gg*1.15&&r>b*1.6)B[y*W+x0]=1}const out=[];for(let y=ay;y<=by;y++)for(let x0=ax;x0<=bx;x0++){const s0=y*W+x0;if(!B[s0]||S[s0])continue;const st=[s0];S[s0]=1;let A=0,sx=0,sy=0;while(st.length){const q=st.pop(),qy=(q/W)|0,qx=q-qy*W;A++;sx+=qx;sy+=qy;for(const z of [q-1,q+1,q-W,q+W])if(z>=0&&z<W*H&&!S[z]&&B[z]){S[z]=1;st.push(z)}}if(A>=3&&A<500)out.push({x:sx/A,y:sy/A,r:7,a:A,kind:"orange"})}return out}
function updateTracks(obs){tracks.forEach(t=>t.seen=false);const assoc=settings().assoc;for(const o of obs){let k=-1,dmin=1e9;tracks.forEach((t,i)=>{if(t.seen||frameNo-t.last>25)return;const d=Math.hypot(t.nom[0]-o.nom[0],t.nom[1]-o.nom[1]);const bonus=(o.kind==="orange"&&t.kind==="orange")?.5:1;if(d*bonus<dmin){dmin=d*bonus;k=i}});if(k>=0&&dmin<assoc){const t=tracks[k];t.rays.push({C:o.C.slice(),d:o.d.slice()});if(t.rays.length>24)t.rays.shift();t.nom=o.nom.slice();t.px=o.x;t.py=o.y;t.kind=o.kind==="orange"?"orange":t.kind;t.last=frameNo;t.seen=true;evaluateTrack(t)}else{const t={rays:[{C:o.C.slice(),d:o.d.slice()}],nom:o.nom.slice(),px:o.x,py:o.y,kind:o.kind,last:frameNo,seen:true,P:o.nom.slice(),depthErr:999,resid:999,base:0,state:"provisional"};tracks.push(t)}}tracks=tracks.filter(t=>t.state==="confirmed"||frameNo-t.last<35);tracks.forEach(evaluateTrack)}
function solve3(A,b){return solve(A,b)}
function triangulate(rays){if(rays.length<2)return null;const A=[[0,0,0],[0,0,0],[0,0,0]],b=[0,0,0];for(const r of rays){const d=unit(r.d),M=[[1-d[0]*d[0],-d[0]*d[1],-d[0]*d[2]],[-d[1]*d[0],1-d[1]*d[1],-d[1]*d[2]],[-d[2]*d[0],-d[2]*d[1],1-d[2]*d[2]]];for(let i=0;i<3;i++){for(let j=0;j<3;j++)A[i][j]+=M[i][j];b[i]+=M[i][0]*r.C[0]+M[i][1]*r.C[1]+M[i][2]*r.C[2]}}const P=solve3(A,b);if(!P)return null;let ss=0;for(const r of rays){const v=sub(P,r.C),perp=sub(v,mul(r.d,dot(v,r.d)));ss+=dot(perp,perp)}return{P:P,resid:Math.sqrt(ss/rays.length)}}
function maxBaseline(rays){let m=0;for(let i=0;i<rays.length;i++)for(let j=i+1;j<rays.length;j++)m=Math.max(m,norm(sub(rays[i].C,rays[j].C)));return m}
function evaluateTrack(t){const s=settings(),tri=triangulate(t.rays);t.base=maxBaseline(t.rays);if(tri){t.P=tri.P;t.resid=tri.resid;t.depthErr=Math.abs(t.P[2]-s.d)}else{t.P=t.nom.slice();t.resid=999;t.depthErr=999}const enough=t.rays.length>=4&&t.base>=s.baseline;if(enough&&t.depthErr<=s.delta&&t.resid<=Math.max(.12,s.delta*1.5))t.state="confirmed";else if(enough&&t.depthErr>s.delta*1.5)t.state="rejected";else t.state="provisional"}
function updateMetrics(nA,nW,nO){const conf=tracks.filter(t=>t.state==="confirmed").length;$("arucoMetric").textContent=nA;$("microMetric").textContent=conf;$("deltaMetric").textContent="±"+$("planeDelta").value+" cm";$("centerMetric").textContent=lastCenterDeltaMm==null?"—":lastCenterDeltaMm.toFixed(1)+" mm";if(!pose){$("poseMetric").textContent="—";$("arucoStatus").textContent="Aucun ArUco détecté.";return}const spreadCm=Math.round(poseSpread*100);$("poseMetric").textContent=poseSpread<.12?"OK":"≈";const ids=markers.map(m=>m.id).sort().join(",");$("arucoStatus").textContent="IDs visibles : "+(ids||"—")+" · dispersion pose "+spreadCm+" cm · "+nW+" blancs · "+nO+" orange"}
function crossMark(px,py,size,col,diag){ctx.strokeStyle=col;ctx.lineWidth=2;ctx.beginPath();if(diag){ctx.moveTo(px-size,py-size);ctx.lineTo(px+size,py+size);ctx.moveTo(px+size,py-size);ctx.lineTo(px-size,py+size)}else{ctx.moveTo(px-size,py);ctx.lineTo(px+size,py);ctx.moveTo(px,py-size);ctx.lineTo(px,py+size)}ctx.stroke()}
function drawLiveOverlay(){if(!live)return;if(pose){const poly=facePolygon(pose,canvas.width,canvas.height,settings().d);if(poly){ctx.strokeStyle="rgba(85,214,190,.9)";ctx.lineWidth=3;ctx.setLineDash([8,5]);ctx.beginPath();poly.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke();ctx.setLineDash([])}}markers.forEach(m=>{ctx.strokeStyle="#6db6ff";ctx.lineWidth=3;ctx.beginPath();m.corners.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.stroke();ctx.fillStyle="#6db6ff";ctx.font="bold 14px sans-serif";ctx.fillText("ID "+m.id,m.center.x+7,m.center.y-7)});const mode=settings().centerMode;if(mode==="compare"){lastWhites.forEach(q=>{ctx.strokeStyle="rgba(255,255,255,.35)";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(q.cx,q.cy);ctx.lineTo(q.ex,q.ey);ctx.stroke();crossMark(q.cx,q.cy,5,"#ffd166",false);crossMark(q.ex,q.ey,5,"#c58cff",true)})}else if(mode==="centroid"){lastWhites.forEach(q=>crossMark(q.cx,q.cy,5,"#ffd166",false))}else{lastWhites.forEach(q=>crossMark(q.ex,q.ey,5,"#c58cff",true))}tracks.forEach(t=>{if(!t.seen)return;let col=t.state==="confirmed"?"#62e392":t.state==="rejected"?"#ff6b6b":"#ffb84d";if(t.kind==="orange")col="#6dcfff";ctx.strokeStyle=col;ctx.lineWidth=t.state==="confirmed"?4:2;ctx.beginPath();ctx.arc(t.px,t.py,t.state==="confirmed"?11:8,0,Math.PI*2);ctx.stroke();if(t.state==="confirmed"){ctx.fillStyle=col;ctx.font="bold 11px sans-serif";ctx.fillText(Math.round(t.depthErr*1000)+" mm",t.px+13,t.py+4)}})}
$("fileBtn").onclick=()=>$("file").click();
$("file").onchange=e=>{const f=e.target.files[0];if(!f)return;const im=new Image();im.onload=()=>setImage(im);im.src=URL.createObjectURL(f)};
$("shotBtn").onclick=()=>{if(!video.videoWidth)return;const q=document.createElement("canvas");q.width=video.videoWidth;q.height=video.videoHeight;q.getContext("2d").drawImage(video,0,0);const im=new Image();im.onload=()=>setImage(im);im.src=q.toDataURL("image/jpeg",.92)};
function setImage(im){live=false;scanning=false;$("scanBtn").textContent="Scanner";const sc=Math.min(780/im.width,1100/im.height,1);canvas.width=Math.max(1,Math.round(im.width*sc));canvas.height=Math.max(1,Math.round(im.height*sc));ctx.drawImage(im,0,0,canvas.width,canvas.height);manualBase=ctx.getImageData(0,0,canvas.width,canvas.height);manualCorners=[];manualCandidates=[];manualPick=false;canvas.hidden=false;video.hidden=true;drawManual();msg("Photo chargée. Utilise 4 coins manuels pour un contrôle ponctuel.")}
$("cornersBtn").onclick=()=>{if(!manualBase){msg("Capture ou charge une photo avant le mode manuel.");return}manualCorners=[];manualCandidates=[];manualPick=true;drawManual();msg("Tape haut-gauche → haut-droite → bas-droite → bas-gauche.")};
function canvasPoint(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
canvas.onpointerdown=e=>{if(live)return;const p=canvasPoint(e);if(manualPick){manualCorners.push(p);if(manualCorners.length===4){manualPick=false;msg("Plan manuel défini. Lance Détecter blanc sur photo.")}drawManual();return}let k=-1,d=1e9;manualCandidates.forEach((q,i)=>{const z=Math.hypot(q.x-p.x,q.y-p.y);if(z<d){d=z;k=i}});if(k>=0&&d<24)manualCandidates[k].keep=!manualCandidates[k].keep;drawManual()};
function drawManual(){if(manualBase)ctx.putImageData(manualBase,0,0);if(manualCorners.length){ctx.strokeStyle="#55d6be";ctx.lineWidth=3;ctx.beginPath();manualCorners.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));if(manualCorners.length===4)ctx.closePath();ctx.stroke()}manualCandidates.forEach(p=>{ctx.strokeStyle=p.keep===false?"#ff6b6b":"#ffb84d";ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,8,0,Math.PI*2);ctx.stroke()})}
$("detectBtn").onclick=()=>{if(!manualBase||manualCorners.length!==4){msg("Définis d’abord les 4 coins sur une photo.");return}manualCandidates=detectWhite(manualBase,manualCorners,60);drawManual();msg(manualCandidates.length+" candidats sur la photo. Touche pour exclure, puis Ajouter vue photo.")};
function homImageToUnit(q){const src=q.map(p=>[p.x,p.y]),dst=[{x:0,y:0},{x:1,y:0},{x:1,y:1},{x:0,y:1}];return homXY(src,dst)}
function mapH(H,p){const d=H[6]*p.x+H[7]*p.y+1;return{x:(H[0]*p.x+H[1]*p.y+H[2])/d,y:(H[3]*p.x+H[4]*p.y+H[5])/d}}
$("addBtn").onclick=()=>{if(manualCorners.length!==4)return;const H=homImageToUnit(manualCorners),s=settings();manualCandidates.filter(p=>p.keep!==false).forEach(p=>{const q=mapH(H,p);if(q.x>=0&&q.x<=1&&q.y>=0&&q.y<=1){tracks.push({rays:[],nom:[q.x*s.S,q.y*s.S,s.d],P:[q.x*s.S,q.y*s.S,s.d],kind:"white",last:frameNo,seen:false,depthErr:0,resid:0,base:0,state:"confirmed",manual:true})}});render3();renderTable();msg("Points photo ajoutés comme validation manuelle.")};
function cubePoint(P){const s=settings();return[P[0],P[2],s.S-P[1]]}
function allConfirmed(){return tracks.filter(t=>t.state==="confirmed")}
function p3(P){const s=settings(),S=s.S;let X=P[0]-S/2,Y=P[1]-S/2,Z=P[2]-S/2,cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),a=cy*X-sy*Y,b=sy*X+cy*Y,c=Z,b2=cp*b-sp*c,z2=sp*b+cp*c,dist=5.4*S/2,sc=three.width*.28/(dist-b2);return[three.width/2+a*sc*3.2,three.height/2-z2*sc*3.2,b2]}
function render3(){const s=settings(),S=s.S;g.fillStyle="#080a0d";g.fillRect(0,0,three.width,three.height);const V=[[0,0,0],[S,0,0],[S,S,0],[0,S,0],[0,0,S],[S,0,S],[S,S,S],[0,S,S]],E=[[0,1],[1,2],[2,3],[3,0],[4,5],[5,6],[6,7],[7,4],[0,4],[1,5],[2,6],[3,7]];g.strokeStyle="#66717d";g.lineWidth=2;E.forEach(e=>{const a=p3(V[e[0]]),b=p3(V[e[1]]);g.beginPath();g.moveTo(a[0],a[1]);g.lineTo(b[0],b[1]);g.stroke()});allConfirmed().forEach(t=>{const q=p3(cubePoint(t.P));g.fillStyle=t.kind==="orange"?"#6dcfff":"#62e392";g.beginPath();g.arc(q[0],q[1],6,0,Math.PI*2);g.fill()});$("count").textContent=allConfirmed().length+" micros reconstruits · plan nominal "+Math.round(s.d*100)+" cm · tolérance ±"+Math.round(s.delta*100)+" cm"}
function renderTable(){const a=allConfirmed();let s="<table><tr><th>ID</th><th>X m</th><th>Y m</th><th>profondeur</th><th>Δplan</th><th>vues</th></tr>";a.slice(0,60).forEach((t,i)=>{s+="<tr><td>M"+String(i+1).padStart(3,"0")+"</td><td>"+t.P[0].toFixed(3)+"</td><td>"+t.P[1].toFixed(3)+"</td><td>"+t.P[2].toFixed(3)+"</td><td>"+(t.depthErr*1000).toFixed(0)+" mm</td><td>"+(t.rays?t.rays.length:1)+"</td></tr>"});$("table").innerHTML=a.length?s+"</table>":""}
function tp(e){const r=three.getBoundingClientRect();return[e.clientX-r.left,e.clientY-r.top]}
three.onpointerdown=e=>{drag=tp(e);three.setPointerCapture(e.pointerId)};three.onpointermove=e=>{if(!drag)return;const p=tp(e);yaw+=(p[0]-drag[0])*.009;pitch=clamp(pitch+(p[1]-drag[1])*.009,-1.3,1.3);drag=p;render3()};three.onpointerup=()=>drag=null;
$("resetBtn").onclick=()=>{yaw=-.65;pitch=.42;render3()};
$("clearBtn").onclick=()=>{tracks=[];markers=[];pose=null;poseSpread=0;lastWhites=[];lastCenterDeltaMm=null;render3();renderTable();updateMetrics(0,0,0);msg("Scan réinitialisé.")};
$("csvBtn").onclick=()=>{let s="id,x_face_m,y_face_m,depth_m,plane_error_m,n_views,kind\n";allConfirmed().forEach((t,i)=>{s+="M"+String(i+1).padStart(3,"0")+","+t.P[0].toFixed(6)+","+t.P[1].toFixed(6)+","+t.P[2].toFixed(6)+","+t.depthErr.toFixed(6)+","+(t.rays?t.rays.length:1)+","+t.kind+"\n"});const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([s],{type:"text/csv"}));a.download="cube_mems_scan.csv";a.click()};
updateMetrics(0,0,0);render3();