(function(){
  const PAT={
    0:["1011","0101","0011","0010"],
    1:["0000","1111","1001","1010"],
    2:["0011","0011","0010","1101"],
    3:["1001","1001","0100","0110"]
  };
  function solve(A,b){const n=b.length,M=A.map((r,i)=>r.slice().concat([b[i]]));for(let k=0;k<n;k++){let m=k;for(let i=k+1;i<n;i++)if(Math.abs(M[i][k])>Math.abs(M[m][k]))m=i;[M[k],M[m]]=[M[m],M[k]];let p=M[k][k];if(Math.abs(p)<1e-9)return null;for(let j=k;j<=n;j++)M[k][j]/=p;for(let i=0;i<n;i++)if(i!==k){let f=M[i][k];for(let j=k;j<=n;j++)M[i][j]-=f*M[k][j]}}return M.map(r=>r[n])}
  function homUnitToImage(q){const s=[[0,0],[1,0],[1,1],[0,1]],A=[],b=[];for(let i=0;i<4;i++){let X=s[i][0],Y=s[i][1],u=q[i].x,v=q[i].y;A.push([X,Y,1,0,0,0,-u*X,-u*Y]);b.push(u);A.push([0,0,0,X,Y,1,-v*X,-v*Y]);b.push(v)}let h=solve(A,b);return h&&h.concat([1])}
  function map(H,u,v){let d=H[6]*u+H[7]*v+1;return{x:(H[0]*u+H[1]*v+H[2])/d,y:(H[3]*u+H[4]*v+H[5])/d}}
  function grayAt(D,W,H,x,y,r){let s=0,n=0;let x0=Math.max(0,Math.floor(x-r)),x1=Math.min(W-1,Math.ceil(x+r)),y0=Math.max(0,Math.floor(y-r)),y1=Math.min(H-1,Math.ceil(y+r));for(let yy=y0;yy<=y1;yy++)for(let xx=x0;xx<=x1;xx++){let i=(yy*W+xx)*4;s+=(D[i]+D[i+1]+D[i+2])/3;n++}return n?s/n:255}
  function rot(g){const n=g.length,o=Array.from({length:n},()=>Array(n));for(let y=0;y<n;y++)for(let x=0;x<n;x++)o[x][n-1-y]=g[y][x];return o}
  function decode(img,corners){const D=img.data,W=img.width,H=img.height,M=homUnitToImage(corners);if(!M)return null;let val=Array.from({length:6},()=>Array(6).fill(255));for(let y=0;y<6;y++)for(let x=0;x<6;x++){let p=map(M,(x+.5)/6,(y+.5)/6);val[y][x]=grayAt(D,W,H,p.x,p.y,1.2)}let border=[];for(let y=0;y<6;y++)for(let x=0;x<6;x++)if(x===0||x===5||y===0||y===5)border.push(val[y][x]);let black=border.reduce((a,b)=>a+b,0)/border.length;let all=val.flat().slice().sort((a,b)=>b-a);let white=all.slice(0,8).reduce((a,b)=>a+b,0)/8;if(white-black<45||black>145)return null;let th=(black+white)/2,obs=Array.from({length:4},(_,y)=>Array.from({length:4},(_,x)=>val[y+1][x+1]>th?1:0));let best=null,g=obs;for(let rr=0;rr<4;rr++){for(const id of [0,1,2,3]){let h=0,p=PAT[id];for(let y=0;y<4;y++)for(let x=0;x<4;x++)if(g[y][x]!==Number(p[y][x]))h++;if(!best||h<best.h)best={id:id,h:h,rot:rr}}g=rot(g)}if(!best||best.h>2)return null;return{...best,contrast:white-black}}
  window.detectFourMarkers=function(img){const D=img.data,W=img.width,H=img.height,N=W*H,B=new Uint8Array(N),S=new Uint8Array(N);for(let p=0;p<N;p++){let i=p*4,L=(D[i]+D[i+1]+D[i+2])/3;if(L<125)B[p]=1}let found=[];for(let y=1;y<H-1;y++)for(let x=1;x<W-1;x++){let s=y*W+x;if(!B[s]||S[s])continue;let st=[s];S[s]=1;let A=0,x0=x,x1=x,y0=y,y1=y,tl=null,tr=null,br=null,bl=null,minS=1e9,maxS=-1e9,minD=1e9,maxD=-1e9;while(st.length){let q=st.pop(),qy=(q/W)|0,qx=q-qy*W;A++;x0=Math.min(x0,qx);x1=Math.max(x1,qx);y0=Math.min(y0,qy);y1=Math.max(y1,qy);let ss=qx+qy,dd=qx-qy;if(ss<minS){minS=ss;tl={x:qx,y:qy}}if(ss>maxS){maxS=ss;br={x:qx,y:qy}}if(dd>maxD){maxD=dd;tr={x:qx,y:qy}}if(dd<minD){minD=dd;bl={x:qx,y:qy}}for(const z of [q-1,q+1,q-W,q+W])if(z>=0&&z<N&&!S[z]&&B[z]){S[z]=1;st.push(z)}}let ww=x1-x0+1,hh=y1-y0+1,ar=ww/hh,fill=A/(ww*hh);if(A<55||A>40000||ww<14||hh<14||ww>260||hh>260||ar<.42||ar>2.4||fill<.12||fill>.92)continue;let corners=[tl,tr,br,bl],dec=decode(img,corners);if(!dec)continue;let cx=corners.reduce((z,p)=>z+p.x,0)/4,cy=corners.reduce((z,p)=>z+p.y,0)/4,score=dec.h+Math.abs(Math.log(ar))*.4;const canonicalCorners=[0,1,2,3].map(i=>corners[(i-dec.rot+4)%4]);found.push({id:dec.id,corners:corners,canonicalCorners:canonicalCorners,center:{x:cx,y:cy},hamming:dec.h,contrast:dec.contrast,score:score,rotation:dec.rot})}
    const best={};found.forEach(m=>{if(!best[m.id]||m.score<best[m.id].score)best[m.id]=m});return Object.values(best);
  };
})();